import type { Project } from '@/types/invitation'

export const DEMO_PROJECT: Project = {
  id: 'demo',
  slug: 'demo',
  template: 'sobre',
  status: 'draft',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  quinceanera_name: 'Alison Galván',
  guest_name: 'Familia García',
  event_date: '2026-11-22T17:00:00',
  rsvp_phone: '4438569931',
  hashtag: '#XVAlison',
  instagram_mode: 'instagram',
  show_instagram_album: true,
  music_url: '/images/esmeralda/musica.mp3',
  hero_photo_url: '/images/esmeralda/foto.jpg',
  parent_names: ['Elías Moises Galván Juárez', 'Esperanza Méndez Hernández'],
  padrinos: ['José Feliciano Hernández', 'María Carolina Escandón Cruz'],
  ceremony: {
    venue: 'Parroquia San Peregrino',
    address: 'Blvd. Solidaridad, Fuentes del Mezquital, 83250 Hermosillo, Son.',
    time: '5:00 PM',
    mapsUrl: 'https://maps.app.goo.gl/EKZpeKCqNpt8PqBo6',
    photoUrl: '/images/esmeralda/iglesia.jpg',
  },
  reception: {
    venue: 'Salón de Evento Villa Toscana',
    address: 'C. Quintero Arce 280, Puerta Grande, 83246 Hermosillo, Son.',
    time: '7:00 PM',
    mapsUrl: 'https://maps.app.goo.gl/NEusLqQqZhirLnCAA',
    photoUrl: '/images/esmeralda/evento.jpg',
  },
  itinerary: [
    { title: 'Misa', time: '05:00 PM', iconSrc: '/images/esmeralda/iglesia.png', description: 'Misa', icon: '/images/esmeralda/iglesia.png' },
    { title: 'Recepción', time: '07:00 PM', iconSrc: '/images/esmeralda/recepcion.png', description: 'Recepción', icon: '/images/esmeralda/recepcion.png' },
    { title: 'Coctelería', time: '08:00 PM', iconSrc: '/images/esmeralda/coctel.png', description: 'Coctelería', icon: '/images/esmeralda/coctel.png' },
    { title: 'Cena', time: '09:00 PM', iconSrc: '/images/esmeralda/comida.png', description: 'Cena', icon: '/images/esmeralda/comida.png' },
    { title: 'Vals', time: '10:20 PM', iconSrc: '/images/esmeralda/vals.png', description: 'Vals', icon: '/images/esmeralda/vals.png' },
    { title: 'Baile', time: '11:30 PM', iconSrc: '/images/esmeralda/baile.png', description: 'Baile', icon: '/images/esmeralda/baile.png' },
    { title: 'Fin del Evento', time: '03:00 AM', iconSrc: '/images/esmeralda/fin.png', description: 'Fin del Evento', icon: '/images/esmeralda/fin.png' },
  ],
  dress_code: { colors: 'Vestimenta Formal', notes: 'El color dorado queda reservado para la quinceañera.' },
  photos: [
    '/images/esmeralda/11.jpg',
    '/images/esmeralda/21.jpg',
    '/images/esmeralda/31.jpg',
    '/images/esmeralda/41.jpg',
    '/images/esmeralda/12.jpg',
    '/images/esmeralda/22.jpg',
  ],
  gift_registry: {
    liverpoolLink: 'https://mesaderegalos.liverpool.com.mx/milistaderegalos/51309081',
    bankAccount: '012345678901234567',
    bankBeneficiary: 'Alison Galván Méndez',
  },
  color_theme: 'rosagold',
  invitation_text: 'Porque este día es muy importante para mí, quiero compartirlo con las personas que llevo en mi corazón.',
  show_video: false,
  video_youtube_id: null,
  video_url: null,
  show_lluvia_sobres: true,
  lluvia_sobres_text: null,
  show_datos_bancarios: true,
  datos_bancarios_text: null,
  show_itinerary: true,
  show_floating_controls: true,
  confirmation_phrase: 'Favor de confirmar asistencia antes del 1 de Noviembre',
  important_info_text: null,
  mesa_regalos_text: null,
  confirmation_highlight_date: null,
  extra_config: {},
  tiene_lista_invitados: false,
  pin_admin: null,
}
