import type { Project } from '@/types/invitation'

export const LOVE_DEMO_PROJECT: Project = {
  id: 'demo-love',
  slug: 'demo-love',
  template: 'love',
  status: 'draft',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  quinceanera_name: 'Camila',
  guest_name: 'Familia García',
  event_date: '2026-11-22T17:00:00',
  rsvp_phone: '4438569931',
  hashtag: '#XVCamila',
  instagram_mode: 'instagram',
  show_instagram_album: true,
  music_url: '/images/love/musica.mp3',
  hero_photo_url: '/images/love/foto1.jpg',
  parent_names: ['Elías Moises Galván Juárez', 'Esperanza Méndez Hernández'],
  padrinos: ['José Feliciano Hernández', 'María Carolina Escandón Cruz'],
  ceremony: {
    venue: 'Parroquia San Peregrino',
    address: 'Blvd. Solidaridad, Fuentes del Mezquital, 83250 Hermosillo, Son.',
    time: '5:00 PM',
    mapsUrl: 'https://maps.app.goo.gl/EKZpeKCqNpt8PqBo6',
    photoUrl: '/images/love/iglesia.jpg',
  },
  reception: {
    venue: 'Salón de Evento Villa Toscana',
    address: 'C. Quintero Arce 280, Puerta Grande, 83246 Hermosillo, Son.',
    time: '7:00 PM',
    mapsUrl: 'https://maps.app.goo.gl/NEusLqQqZhirLnCAA',
    photoUrl: '/images/love/evento.jpg',
  },
  itinerary: [
    { title: 'Misa',         time: '05:00 PM', iconSrc: '/images/love/misa.png',     description: 'Misa',         icon: 'misa.png'     },
    { title: 'Recepción',    time: '07:00 PM', iconSrc: '/images/love/recepcion.png', description: 'Recepción',    icon: 'recepcion.png' },
    { title: 'Coctelería',   time: '08:00 PM', iconSrc: '/images/love/coctel.png',   description: 'Coctelería',   icon: 'coctel.png'   },
    { title: 'Cena',         time: '09:00 PM', iconSrc: '/images/love/comida.png',   description: 'Cena',         icon: 'comida.png'   },
    { title: 'Vals',         time: '10:20 PM', iconSrc: '/images/love/vals.png',     description: 'Vals',         icon: 'vals.png'     },
    { title: 'Baile',        time: '11:30 PM', iconSrc: '/images/love/baile.png',    description: 'Baile',        icon: 'baile.png'    },
    { title: 'Fin del Evento', time: '03:00 AM', iconSrc: '/images/love/fin.png',   description: 'Fin del Evento', icon: 'fin.png'    },
  ],
  dress_code: { colors: 'Vestimenta Formal', notes: 'El color dorado queda reservado para la quinceañera.' },
  photos: [
    '/images/love/foto2.jpg',
    '/images/love/foto3.jpg',
    '/images/love/foto4.jpg',
    '/images/love/foto5.jpg',
    '/images/love/foto6.jpg',
    '/images/love/foto7.jpg',
  ],
  gift_registry: {
    liverpoolLink: 'https://mesaderegalos.liverpool.com.mx/milistaderegalos/51309081',
    bankAccount: '012345678901234567',
    bankBeneficiary: 'Alison Galván Méndez',
  },
  color_theme: 'rosagold',
  invitation_text: 'Porque este día es muy importante para mí, quiero compartirlo con las personas que llevo en mi corazón.',
  show_video: false,
  video_youtube_id: null,
  video_url: null,
  show_lluvia_sobres: true,
  lluvia_sobres_text: null,
  show_datos_bancarios: true,
  datos_bancarios_text: null,
  show_itinerary: true,
  confirmation_phrase: 'Favor de confirmar asistencia antes del 1 de Noviembre',
  confirmation_highlight_date: null,
  extra_config: {},
  tiene_lista_invitados: false,
  pin_admin: null,
}
